### ISSUE TITLE
TestOpenStoreCollection panic

### ISSUE THREAD

**Issue by steveyen** [couchbase/moss#46]
Saw this one time only so far (sporadic)...
> === RUN   TestOpenStoreCollection
> --- FAIL: TestOpenStoreCollection (0.21s)
> 	store_test.go:1035: expected reopen store to work
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1180dfd]
> 
> goroutine 6028 [running]:
> testing.tRunner.func1(0xc4200709c0)
> 	/usr/local/go/src/testing/testing.go:622 +0x29d
> panic(0x11cb760, 0x12f0710)
> 	/usr/local/go/src/runtime/panic.go:489 +0x2cf
> _/Users/steveyen/dev/couchbase-server.spock/godeps/src/github.com/couchbase/moss.TestOpenStoreCollection(0xc4200709c0)
> 	/Users/steveyen/dev/couchbase-server.spock/godeps/src/github.com/couchbase/moss/store_test.go:1038 +0xebd
> testing.tRunner(0xc4200709c0, 0x120e038)
> 	/usr/local/go/src/testing/testing.go:657 +0x96
> created by testing.(*T).Run
> 	/usr/local/go/src/testing/testing.go:697 +0x2ca
> exit status 2
> FAIL	_/Users/steveyen/dev/couchbase-server.spock/godeps/src/github.com/couchbase/moss	18.562s

**Comment by steveyen** [comment]
Might be related to... http://review.couchbase.org/#/c/82704/1 ?

**Comment by steveyen** [comment]
Whoops, the panic is a red herring -- the real problem is this...
    store_test.go:1035: expected reopen store to work
